server:
  servlet:
    context-path: /service-main
  port: 8502

spring:
  application:
    name: Componente de Promociones
    version: v1
    title: Promociones

  datasource:
    url: jdbc:postgresql://37.60.238.21:5432/promociones_db
    username: promouser
    password: promo123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

inventario:
  url: https://endpoints-production-4a52.up.railway.app/api

logging:
  level:
    com.componente.promociones.model.dto.integraciones.lealtad.inventario.InventarioClient: DEBUG
    feign: DEBUG